# Generated by Django 6.0.6 on 2026-06-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatieVacanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_original', models.URLField(max_length=500)),
                ('tara', models.CharField(max_length=100)),
                ('locul', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('Natura', 'Natura'), ('Urban', 'Urban'), ('Mixed', 'Mixed')], max_length=50)),
                ('tip_activitate', models.TextField()),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
